name: IC-3.8-2024-06-08
channels:
- conda-forge
- defaults
dependencies:
- python       = 3.8
# *REMEMBER TO CHANGE CONDA_ENV_TAG WHEN CHANGING VERSION NUMBERS*
- cython       = 0.29.24
- jupyter      = 1.0.0
- jupyterlab   = 3.2.1
- matplotlib   = 3.4.3
- networkx     = 2.6.3
- notebook     = 6.4.5
- numpy        = 1.23.1
- pandas       = 1.3.4
- seaborn      = 0.11.2
- pymysql      = 1.0.2
- pytables     = 3.7.0
- pytest       = 6.2.4
- scipy        = 1.9.3
- sphinx       = 4.2.0
- tornado      = 6.1
- flaky        = 3.7.0
- hypothesis   = 6.14.1
- pytest-xdist = 2.3.0
- coverage     = 5.5
- pip          = 21.2.4
- setuptools   = 58.0.4
- scikit-learn = 1.3.0

- pip:
  - pytest-instafail==0.4.2
