#!/usr/bin/env python
"""
Suppress output and prompt numbers in git version control.
"""


import sys
import json
def strip_output_from_cell(cell):
    if "outputs" in cell:
        cell["outputs"] = []
    if "execution_count" in cell:
        cell["execution_count"] = None
    if "metadata" in cell:
        cell["metadata"]["collapsed"] = False
nb = sys.stdin.read()
json_in = json.loads(nb)

for cell in json_in["cells"]:
    strip_output_from_cell(cell)

json.dump(json_in, sys.stdout, sort_keys=True, indent=1, separators=(",",": "), ensure_ascii=False)
sys.stdout.write('\n')
