files_in    = "/jobs/d9a93599-e866-4123-aa05-44cb1931c05e/run_15271_0296_ldc1_trg1.waveforms.h5"
file_out    = "/jobs/d9a93599-e866-4123-aa05-44cb1931c05e/run_15271_0296_ldc1_trg1.v2.3.1.20250429.Kr.irene.h5"
compression = "ZLIB4"
run_number  = 15271
detector_db = "next100"
print_mod   = 10000
event_range = all


# max number of events to run
event_range = all

#n_baseline     =   90000 ### TO BE CHECKED!!!
n_baseline = 70000

# Set MAU for calibrated sum
n_maw   = 100
thr_maw =   10 * adc

# Set thresholds for calibrated sum
thr_csum_s1 = 0.1 * pes 
thr_csum_s2 = 0.5 * pes  

# Set MAU thresholds for SiPM
thr_sipm      = 2.0 * pes
thr_sipm_type = common

# Set parameters to search for S1
s1_tmin       =   0 * mus # 
s1_tmax       =   1379 * mus # 
s1_stride     =   4       # used to be 4 for some reason 
s1_lmin       =   5       # 5 x 25 = 125 ns
s1_lmax       =  40       # 40 x 25 = 1 mus
s1_rebin_stride = 1       # Do not rebin S1 by default

# Set parameters to search for S2
s2_tmin     =   1379 * mus  # do not consider full window to speed up 
s2_tmax     =   1600 * mus  # end of the window
s2_stride   =     10        #  40 x 25 = 1   mus
s2_lmin     =    160        # 160 x 25 = 4 mus
s2_lmax     = 100000        # maximum value of S2 width
s2_rebin_stride = 40        # Rebin by default, 40x25 ns time bins to make one 1us time bin

# Set S2Si parameters
thr_sipm_s2 = 5.0 * pes  # Threshold for the full sipm waveform

# Added by me
pmt_samp_wid  = 25 * ns
sipm_samp_wid =  1 * mus
