files_in    = ""
file_out    = ""
compression = "ZLIB4"
run_number  = 15271
detector_db = "next100"
print_mod   = 10000
event_range = all

drift_v     = 0.87 * mm / mus # z=DT as different HV will be used

s1_params = dict(
s1_nmin     =    1,
s1_nmax     =    127,
s1_emin     =  0.1 * pes,
s1_emax     =  1e9 * pes,
s1_wmin     =  125 * ns,
s1_wmax     =  1000 * ns,
s1_hmin     = 0.25 * pes,
s1_hmax     =  1e9 * pes,
s1_ethr     =    0 * pes,
)

s2_params = dict(
s2_nmin     =    1,
s2_nmax     =   50,
s2_emin     =  1e3 * pes,
s2_emax     =  1e9 * pes,
s2_wmin     =    2 * mus,
s2_wmax     =  1e4 * mus,
s2_hmin     =   50 * pes,
s2_hmax     =  1e9 * pes,
s2_ethr     =    0 * pes,
s2_nsipmmin =    1,
s2_nsipmmax = 6000, # no cut
)

rebin = 2
rebin_method = stride

sipm_charge_type = raw
#fiducial_fraction = 0.95

global_reco_algo = corona
global_reco_params = dict(
  Qthr=10*pes,
  Qlm =20*pes,
  lm_radius=1,
  new_lm_radius=2*np.sqrt(2)*15.55 + 0.1,
  msipm=1,
  consider_masked=False,
)

same_peak = True

# TO BE MODIFIED WHEN REAL MAPS AVAILABLE!!!!!!
corrections_file = '/Users/samuele/Software/IC/invisible_cities/database/test_data/kr_emap_xy_100_100_mc.h5'
apply_temp       = False

q_thr = 5 * pes