import numpy as np
import numexpr as ne

from typing import Tuple
from typing import Callable

from scipy.stats  import rv_continuous
from scipy.sparse import csr_matrix

##################################
############## PES ###############
##################################
def pes_at_pmts(LT      : Callable  ,
                photons : np.ndarray,
                xs      : np.ndarray,
                ys      : np.ndarray,
                zs      : np.ndarray = None)->np.ndarray:
    """Compute the pes generated in each PMT from photons generated at some point

    Parameters:
        :LT: function
            The Liht Table in functional form
        :photons: np.ndarray
            The photons generated at each hit (in the active volume
            for the S1 and in the EL for S2)
        :xs, ys, zs: np.ndarray
            hit position (zs=None for S2)
    Returns:
        :pes: np.ndarray
            photoelectrons at each PMT produced by each hit.
            Shape is (nsensors, nhits)
    """
    if np.any(zs): #S1
        pes = photons[:, np.newaxis] * LT(xs, ys, zs)
    else:          #S2
        pes = photons[:, np.newaxis] * LT(xs, ys)
    pes = np.random.poisson(pes)
    return pes.T


def pes_at_sipms(PSF        : Callable,
                 datasipm   : np.ndarray,
                 sipm_frame : float,
                 photons    : np.ndarray,
                 xs         : np.ndarray,
                 ys         : np.ndarray)->Tuple[csr_matrix, np.ndarray]:
    """Compute the pes generated in each framed SIPM from photons generated at some point

    Parameters:
        :PSF: function
            The PSF in functional form
        :datasipm: pd.Dataframe
            sipm data from database (load_db.DataSiPM)
        :sipm_frame: float
            just SIPMs inside a square between ((xmin, ymin)-sipm_frame, (xmax, ymax)+sipm_frame) will
            be considered. Recomended value is the PSF maximum distance, but it can be lower if PSF
            maximum distance is irrelevantly large.
        :photons: np.ndarray
            The photons generated at each hit (in the active volume
            for the S1 and in the EL for S2)
        :xs, ys, zs: np.ndarray
            hit position (zs=None for S2)
    Returns:
        :pes: np.ndarray
            photoelectrons at framed SIPM produced by each hit.
            Shape is (nsensors, nhits)
        :sipm_ids: np.ndarray
            SIPM ids (from database indexes) of considered SIPMs
    """
    xsensors, ysensors = datasipm["X"].values, datasipm["Y"].values

    ######### TP FRAMING #############
    xmin, xmax = np.min(xs), np.max(xs)
    ymin, ymax = np.min(ys), np.max(ys)

    x1, x2 = xmin - sipm_frame , xmax + sipm_frame
    y1, y2 = ymin - sipm_frame , ymax + sipm_frame

    selx = (x1<xsensors) & (xsensors<x2)
    sely = (y1<ysensors) & (ysensors<y2)
    sel = selx & sely

    seldatasipm = datasipm[sel]
    sipmids = seldatasipm.index.values
    xsensors, ysensors = seldatasipm["X"].values, seldatasipm["Y"].values

    ########## PES at SIPMS###############
    xdistance = xs[:, np.newaxis] - xsensors
    ydistance = ys[:, np.newaxis] - ysensors
    # distances = (xdistance**2 + ydistance**2)**0.5
    distances = ne.evaluate("(xdistance**2 + ydistance**2)**0.5")

    psf = PSF(distances.T)
    nsensors, nhits, npartitions = psf.shape
    psf = csr_matrix(np.reshape(psf, (nsensors, nhits*npartitions)))
    pes = csr_matrix(np.repeat(photons, npartitions))

    pes = psf.multiply(pes)
    pes.data = np.random.poisson(pes.data/npartitions)
    return pes, sipmids


##################################
############## TIMES #############
##################################
class S1_TIMES(rv_continuous):
    """S1 times distribution generator.
    Following distribution 0.1*exp(t/4.5) + 0.9*exp(t/100)"""

    def __init__(self):
        super().__init__(a=0)

    def _pdf(self, x):
        return (0.1*np.exp(-x/4.5) + 0.9*np.exp(-x/100))*1/(0.1*4.5 + 0.9*100)

generate_S1_time = S1_TIMES()

def generate_S1_times_from_pes(S1pes_at_pmts:np.ndarray)->list:
    """Given the S1pes_at_pmts, this function returns the times at which the pes
    are be distributed (see generate_S1_time function).
    It returns a list whose elements are the times at which the photoelectrons in that PMT
    are generated.

    Parameters:
        :S1pes_at_pmts: np.ndarray
            the pes at each PMT generated by each hit
    Returns:
        :S1times: list[np.ndarray,..]
            Each element are the S1 times for a PMT. If certain sensor
            do not see any pes, the array is empty.
    """
    S1pes_pmt = np.sum(S1pes_at_pmts, axis=1)
    S1times = [generate_S1_time.rvs(size=pes) for pes in S1pes_pmt]
    return S1times
