#!/usr/bin/env python
import sys
import re

header = "(.*)(=+) warnings summary (=+)(.*)"   # <color> === title === <color>
footer = "(.*)(=+) (.+) warnings (.+) (=+)(.*)" # <color> === x passed y warnings in z seconds === <color>

found = False
doit  = False
for line in map(str.strip, open(sys.argv[1])):
    if re.match(header, line): doit=True

    if doit:
        found = True
        print(line)

    if re.match(footer, line): doit=False
