files_in    = '/home/investigator/Documents/HD_Demo/analysis/data/test/Run851/run_851_*_ldc1_trg0.waveforms.h5'
file_out    = '/home/investigator/Documents/HD_Demo/analysis/data/test/run_851_ercilia.h5'
compression = 'ZLIB4'
print_mod   = 1
event_range = 1000000

run_number    = 851
detector_db   = 'hddemo'

# Histogram bins
min_bin   = - 49.5
max_bin   =  200
bin_width =    1


proc_mode        = subtract_mode
number_integrals =     10000
integral_start   =    1
integral_width   =     2
integrals_period =    2