files_in    = '/home/investigator/Documents/HD_Demo/analysis/data/test/Run643/run_643_*_ldc1_trg0.waveforms.h5'
file_out    = '/home/investigator/Documents/HD_Demo/analysis/data/test/run_643_ercilia.h5'
compression = 'ZLIB4'
print_mod   = 1
event_range = 100000

run_number    = 643
detector_db   = 'hddemo'

# Histogram bins
min_bin   = -3000
max_bin   =  40000
bin_width =    1


proc_mode        = subtract_mode
number_integrals =     100
integral_start   =    1
integral_width   =     2
integrals_period =    2