files_in    = '/home/investigator/Documents/HD_Demo/analysis/data/test/Run643/run_643_000*_ldc1_trg0.waveforms.h5'
file_out    = '/home/investigator/Documents/HD_Demo/analysis/data/test/run_643_ercilia_testing.h5'
compression = 'ZLIB4'
print_mod   = 1
event_range = 1000000

run_number    = 643
detector_db   = 'hddemo'
amplification = True

# Histogram bins
min_bin   = -10000
max_bin   =  50000
bin_width =    10


proc_mode        = subtract_mode
number_integrals =     10000
integral_start   =    1
integral_width   =     2
integrals_period =    2