files_in = '/Users/maria/NEXT/NEXT-100/data/15504/*/*.h5'
file_out = 'test.h5'
compression = 'ZLIB4'
event_range = all
# run number 0 is for MC
run_number = 15504
# Detector database used
detector_db = 'next100'


pre_map = '/Users/maria/IC/invisible_cities/icaros/examples/preliminary_map_15502.h5'
norm_method = maximum

# ------ Selection parameters ------
dtrms2_low = lambda dt: -0.7 + 0.030 * (dt-20)
dtrms2_upp = lambda dt: 2.6 + 0.036 * (dt-20)
low_xrays = 36
high_xrays= 47
low_S2t = 1.38e6
high_S2t = 1.44e6
R_max = 450
low_DT = 20
high_DT = 1350
low_nsipm = 0
high_nsipm= 30


# ------ Create map parameters ------
xy_range = (-450, 450)
dt_range = (20, 1350)
xy_nbins = 100
dt_nbins = 10
fit_function = gaussian_fit
nbins_S2e = 100
S2e_range = (1000, 20000)


# ------ Time evolution parameters ------
slice_hours = 2
col_name1 = 'Ec'
col_name2 = 'Ec_2'
x0 = 0
y0 = 0
shape = circle
shape_size = 100
dtbins_dv = np.linspace(1200, 1400)
s1_DTrange = (1000, 1350)
bins_Ec  = np.linspace(20, 60, 101)
error = False

# ------ Save map parameters -----
name = '3Dmap_test.h5'

# ------ Make control plots parameters ------
plots_out = f'plots_out_{run_number}'
ebins1 = np.linspace(0, 50, 101)
ns1bins = np.linspace(0, 10, 10)
s1hbins = np.linspace(0, 20, 100)
s1wbins = np.linspace(50, 1000, 20)
ebins2 = np.arange(4e3, 1e4, 51)
ns2bins = np.linspace(0, 20, 20)
s2hbins = np.linspace(0, 3e3, 100)
s2qbins =  np.linspace(0, 1.5e3, 100)
qmaxbins = np.linspace(0, 300, 100)
s2wbins = np.linspace(0, 60, 100)
dtrms2_low = lambda dt: -0.7 + 0.030 * (dt -20)
dtrms2_upp = lambda dt: 2.6 + 0.036 * (dt-20)
dtrms2_cen = lambda dt:  1.0 + 0.033 * (dt-20)
dtbins2 = np.linspace(0, 1400, 51)
bins = 100
dtr2_bins = (20, 20)
statistic = 'mean'
x0 = 0
y0 = 0
shape = circle
shape_size = 100
xy_range_plot = np.linspace(-500, 500, 100)