files_in    = '/Users/maria/NEXT/NEXT-100/data/MC/kr/fullsim/202608/sophronia/*.h5'
file_out    = 'MC_3Dmap_fullsim_202608_50bins.h5'
compression = 'ZLIB4'
event_range = all

# run number 0 is for MC
run_number = 0

# Detector database used
detector_db = 'next100'

pre_map     = '/Users/maria/IC/invisible_cities/database/test_data/preliminary_map_15502.h5'
norm_method = maximum

# ------ Selection parameters ------
dtrms2_low = lambda dt: -0.7 * np.ones_like(dt) #less than zrms2.min()
dtrms2_upp = lambda dt: 999998000002.0 * np.ones_like(dt) #greater than zrms2.max()
dtrms2_cen = lambda dt: 0.0 * (dt-20)
low_xrays  = 0
high_xrays = 1e6
low_S2t    = 0
high_S2t   = 1e12
R_max      = 500
low_DT     = 20
high_DT    = 1350
low_nsipm  = 0
high_nsipm = 1000

# ------ Create map parameters ------
xy_range     = (-500, 500)
dt_range     = (20, 1350)
xy_nbins     = 100
dt_nbins     = 10
S2e_range    = (1000, 20000)
fit_function = gaussian
min_events   = 40
nbins        = 100

# ------ Time evolution parameters ------
slice_hours = 1e12
x0          = 0
y0          = 0
shape       = circle
shape_size  = 100
dtbins_dv   = np.linspace(1200, 1400)
s1_DTrange  = (1000, 1350)
bins_Ec     = np.linspace(20, 60, 101)
error       = False

# ------ Make control plots parameters ------
plots_out     = f'plots_out_{run_number}'
ebins1        = np.linspace(0, 50, 101)
ns1bins       = np.linspace(0, 10, 10)
s1hbins       = np.linspace(0, 20, 100)
s1wbins       = np.linspace(50, 1000, 20)
ebins2        = np.arange(4e3, 1.4e4, 51)
ns2bins       = np.linspace(0, 20, 20)
s2hbins       = np.linspace(0, 3e3, 100)
s2qbins       = np.linspace(0, 1.5e3, 100)
qmaxbins      = np.linspace(0, 300, 100)
s2wbins       = np.linspace(0, 60, 100)
dtbins2       = np.linspace(0, 1400, 51)
high_S2e      = 1.4e4
low_S2e       = 4e3
high_DT       = 1350
low_DT        = 20
bins          = 100
dtr2_bins     = (20, 20)
statistic     = 'mean'
xy_range_plot = np.linspace(-500, 500, 100)
